spring:
  application:
    name: spring-boot-react-template
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
